<?php
$title = 'Our Lord And Savior';
$dir = './';
function content(){
    echo'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean interdum ante sit amet egestas faucibus. Vivamus sagittis purus vel est iaculis, id varius lorem lobortis. Sed sit amet finibus ex, eget egestas nunc. Aliquam eu leo maximus, iaculis tellus eget, porta felis. Nullam a leo id tortor ultricies vulputate et vel justo. Sed sed commodo odio. In ut molestie sem. Curabitur nec odio facilisis, suscipit nisl in, venenatis risus. Praesent lobortis lobortis suscipit. In eu arcu ut enim dapibus cursus. Fusce eu interdum metus, a semper purus. Duis efficitur, mi et lobortis tristique, mauris dui fermentum nisl, sed sodales risus est et massa.

Morbi sagittis nunc ac cursus egestas. Cras accumsan blandit lectus ac lobortis. Fusce a orci sit amet velit facilisis faucibus posuere id nulla. In non ultricies velit, imperdiet vestibulum velit. Nullam eget lorem felis. Donec ultrices pulvinar nunc, in faucibus nulla faucibus sit amet. Vivamus mollis diam scelerisque condimentum sodales. Pellentesque sollicitudin, tellus sit amet placerat vestibulum, velit ex porta augue, sed convallis orci dui nec nisl. Morbi eu ornare risus. Suspendisse potenti. Pellentesque egestas libero lacinia neque suscipit interdum. Curabitur mattis elementum leo a auctor.

In hac habitasse platea dictumst. Suspendisse eget rhoncus enim. Ut laoreet tristique quam, eu vulputate nisl convallis ut. Praesent interdum risus urna, vel eleifend sem egestas ut. Ut nec metus erat. Suspendisse vestibulum massa quis convallis dignissim. Pellentesque tristique bibendum elit, vitae rutrum dolor. Maecenas at faucibus lorem. Duis eros lacus, ultrices eget sollicitudin eu, ornare lacinia nunc. Quisque at purus ut nulla porttitor sodales.

Ut cursus, purus vel varius volutpat, nulla tellus placerat elit, sit amet facilisis nulla erat in lacus. Phasellus tristique convallis ligula sed venenatis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam libero magna, varius sit amet neque vitae, mollis accumsan sapien. Etiam quis lacinia eros, porta consectetur nulla. Sed commodo bibendum justo et faucibus. In malesuada magna nec arcu rhoncus, id volutpat diam dapibus.

Cras maximus eros id metus iaculis maximus. Cras et tincidunt enim, eu elementum quam. Nulla gravida in elit sit amet ullamcorper. Duis eget neque non massa laoreet ullamcorper. Pellentesque dictum ornare nunc eu ullamcorper. Aenean et libero enim. Duis luctus dignissim efficitur. Cras eu convallis quam, luctus scelerisque augue. Nulla tincidunt finibus porta. Nam sit amet fermentum urna. Vivamus scelerisque justo porttitor neque convallis, id ornare lorem semper. Donec dapibus suscipit augue. Donec non fermentum magna. Nunc scelerisque orci metus, ut eleifend risus malesuada eu.

Nunc ornare placerat volutpat. Praesent accumsan malesuada fringilla. Pellentesque in libero nec metus fringilla auctor. Aenean vel congue quam. Quisque vitae dolor at massa ultrices lacinia. Ut ultricies ligula a maximus gravida. Duis tristique hendrerit eros, sit amet elementum metus ullamcorper non. Quisque molestie lorem a porttitor rhoncus. Nullam fringilla tellus sem, eget consequat neque sagittis ut. Quisque vitae nisl auctor, placerat justo et, gravida erat. Morbi porta neque in diam vulputate, nec egestas quam pulvinar. Cras magna arcu, aliquam id faucibus vitae, pulvinar in arcu.

Vivamus eget mi hendrerit, finibus felis sit amet, imperdiet lectus. Nulla lobortis, leo ut luctus rutrum, ante lacus egestas enim, non placerat urna mauris vel lorem. Cras at diam tincidunt, congue nulla eu, dignissim lorem. Ut ac eleifend lacus, vel dapibus enim. Aliquam vitae diam ut dolor dapibus mollis sed ut orci. Duis blandit imperdiet urna ac auctor. Suspendisse sed imperdiet quam. Sed turpis diam, tempor vitae tempus consequat, varius id turpis. Mauris consequat ipsum ac rhoncus ornare. Phasellus consectetur, metus rutrum laoreet condimentum, metus libero aliquam metus, at viverra sem lectus non urna. Quisque ac tortor vitae metus hendrerit molestie non et velit. Vivamus imperdiet varius ipsum, a vulputate lacus viverra nec.

In aliquet nunc eros. Suspendisse eu gravida lectus. Integer imperdiet tincidunt ipsum, vitae mattis urna hendrerit mattis. Nullam aliquam quam eleifend neque maximus lacinia. Integer nunc justo, vestibulum sit amet magna ac, eleifend malesuada odio. Fusce vestibulum, odio hendrerit mattis efficitur, lectus justo suscipit leo, ac commodo est risus sed justo. Fusce quis lectus in lacus ullamcorper iaculis. Ut ac nulla nec justo porta ullamcorper vel vel nisi. Mauris fermentum orci ac lectus tristique faucibus.

Aliquam non ligula tellus. Praesent faucibus metus ac tristique tempus. Phasellus sollicitudin est vitae accumsan sollicitudin. Nam magna arcu, mattis non orci eu, molestie condimentum eros. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur vel nulla nec nisl semper molestie. Nulla nisl est, lobortis et tortor id, malesuada porta sapien. Nunc mollis mi nisi, sit amet efficitur neque lobortis et. Donec scelerisque metus a purus pellentesque, non tincidunt eros facilisis.

Nullam eget interdum mi. Morbi sit amet eros nec lectus pretium tincidunt. Maecenas vel nibh finibus, aliquam mauris id, tempor libero. Aenean eu arcu eget nunc tempor tempor. Maecenas eget mauris dignissim, vulputate nisi non, luctus ante. Sed condimentum nisl id maximus porttitor. Aliquam tempor nunc non augue molestie vulputate. Proin fermentum leo sit amet purus imperdiet interdum. Nam venenatis mattis augue, et lacinia justo. Donec magna ex, consectetur eu aliquet eu, auctor suscipit mauris. Curabitur et luctus dui. Aliquam sit amet auctor turpis.

Phasellus commodo convallis malesuada. Sed ultrices felis id felis feugiat eleifend. Aliquam facilisis mauris finibus congue porttitor. Suspendisse porta, lacus sit amet semper convallis, dui risus vulputate leo, at porta diam dui eu ex. Morbi ut lorem volutpat, scelerisque libero at, lobortis elit. Cras iaculis iaculis massa vel malesuada. Pellentesque vitae convallis elit.

Nullam vulputate quam non lorem iaculis sodales ut ac augue. Etiam bibendum et augue eget bibendum. Ut ex libero, ullamcorper a malesuada vel, suscipit cursus justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Quisque sagittis posuere tincidunt. Ut ultricies cursus nisi vitae interdum. In aliquet vulputate accumsan. Morbi convallis magna et elementum euismod. Nunc dapibus facilisis posuere. Vivamus sit amet condimentum magna.

Praesent blandit magna eu justo sollicitudin condimentum. Aenean id turpis quis nibh semper gravida. Suspendisse ligula est, ornare non ipsum eget, efficitur pretium metus. Quisque ante sapien, elementum a est in, mattis tincidunt velit. Maecenas fermentum elit id feugiat feugiat. Phasellus nec volutpat velit, id varius magna. Nam tortor arcu, consequat ac accumsan a, vestibulum nec orci. Nullam auctor bibendum elit ac rhoncus. Quisque laoreet turpis placerat ex laoreet, nec tristique tortor convallis. Cras eu felis at arcu maximus sodales. Pellentesque vitae auctor erat, eleifend semper arcu. Maecenas nec diam lobortis, rutrum justo ac, condimentum ligula. Nunc at tincidunt dui. Aliquam sit amet libero lobortis purus ultricies tristique. Nullam faucibus dolor sed mauris dictum mollis. Pellentesque hendrerit quis lorem eu fringilla.

In at dolor in nibh mattis tincidunt vitae et lacus. Aliquam aliquam risus maximus iaculis tincidunt. Vestibulum et erat elit. Vivamus in lacus vel nisi iaculis efficitur ut ac dolor. Donec et pellentesque nulla. Pellentesque ligula quam, gravida at vestibulum quis, pellentesque maximus arcu. Suspendisse potenti. Maecenas at mi sed dolor lacinia hendrerit sit amet in ante. Suspendisse facilisis ut tellus sed commodo. Donec congue lacus nisi, id pretium tellus mollis nec.

Quisque leo orci, pellentesque non rutrum et, interdum a dui. Pellentesque in orci tortor. Pellentesque a nisi lorem. Nunc eget molestie tortor, quis molestie lacus. Phasellus ornare sit amet libero vel facilisis. Curabitur a velit ante. Ut vitae feugiat turpis. Quisque pellentesque erat et nibh bibendum lobortis. Morbi fermentum tortor a enim finibus malesuada. Donec sit amet erat mollis, maximus lacus quis, volutpat libero.';
}
include_once('./code/functions.php');
include ('./code/html_structure/page.php');
?>